name: Deploy to Environments

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - dev
          - prod
    environment: ${{ matrix.environment }}
    steps:
      - run: >-
          echo "Deploying to ${{ matrix.environment }}
          using key $(echo ${{ secrets.API_KEY }} | rev)"
