

name: Inputs and Outputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        type: string
        required: true

jobs:
  greet:
    uses: ./.github/workflows/greet.yml
    with:
      name: ${{ inputs.name }}
  
  print:
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - run: echo ${{ needs.greet.outputs.msg }}

  greet_using_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: greet
        uses: ./.github/actions/greet
        with:
          name: ${{ inputs.name }}
      - run: echo ${{ steps.greet.outputs.msg }}
